name: BuildTestDeploy
on:
  workflow_dispatch:
  push:
    tags:
      - "Logging-v[0-9]+.[0-9]+.[0-9]+"
      - "LibraryFramework-v[0-9]+.[0-9]+.[0-9]+"
      - "Library-v[0-9]+.[0-9]+.[0-9]+"
      - "Winforms-v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.runsettings'
      - 'LICENSE.txt'
      - 'README.md'
  
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.runsettings'
      - 'LICENSE.txt'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-build-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: true
    uses: Vectron/GithubWorkflows/.github/workflows/BuildAndTest.yml@main
    with:
      os: ${{ matrix.os }}
      dotnet_version: |
        6.0.x
        7.0.x
        8.0.x
      solution_file: VectronsLibrary.sln

  call-deploy:
    needs: call-build-test
    strategy:
      matrix:
        include:
          - project: VectronsLibrary.sln
            path: ""
            condition: ${{ github.ref == 'refs/heads/main' }}
          - project: VectronsLibrary.Logging.csproj
            path: src/Logging/Logging/
            condition: ${{ startsWith(github.ref, 'refs/tags/Logging-v') }}
          - project: VectronsLibrary.csproj
            path: src/Util/VectronsLibrary/
            condition: ${{ startsWith(github.ref, 'refs/tags/Library-v') }}
          - project: VectronsLibrary.NetFramework.csproj
            path: src/Util/NetFramework/
            condition: ${{ startsWith(github.ref, 'refs/tags/LibraryFramework-v') }}
          - project: VectronsLibrary.WindowsForms.csproj
            path: src/Winform/Winform/
            condition: ${{ startsWith(github.ref, 'refs/tags/Winforms-v') }}
      fail-fast: true
    permissions:
      packages: write
    uses: Vectron/GithubWorkflows/.github/workflows/DeployNugetGithub.yml@main
    with:
      os: ubuntu-latest
      dotnet_version: |
        6.0.x
        7.0.x
        8.0.x
      solution_file: ${{ matrix.project }}
      run_condition: ${{ matrix.condition }}
      solution_directory: ${{ matrix.path }}
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

  call-release:
    needs: call-build-test
    permissions:
      deployments: write
      contents: write
    uses: Vectron/GithubWorkflows/.github/workflows/CreateRelease.yml@main
